name: "Mirror nginx-quic to GitHub"
on:
  schedule:
    - cron: "45 6 * * *"
  push:
  pull_request:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: "Mirror nginx-quic to GitHub"
        shell: bash
        run: |
          set -e

          sudo apt-get update -y
          sudo apt-get install -y git-remote-hg

          # write ssh key to ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub

          git clone git@github.com:nginx-quic/nginx-quic.git
          cd nginx-quic

          git remote add hg "hg::https://hg.nginx.org/nginx-quic"
          git pull hg master

          git push origin --all
          git push origin --tags
